CREATE TABLE PRODUCT(
PRODUCT_ID INT NOT NULL AUTO_INCREMENT,
CATEGORY_ID INT NOT NULL,
PRODUCT_NAME VARCHAR(200) NOT NULL,
PRODUCT_DETAILS LONGTEXT,
PRODUCT_IMAGE_URL VARCHAR(500),
PRODUCT_DEAL_URL VARCHAR(500),
PRODUCT_VENDOR VARCHAR(50),
PRODUCT_ACTUAL_PRICE DECIMAL(8,2),
PRODUCT_SALE_PRICE DECIMAL(8,2),
PRODUCT_COUPON VARCHAR(25),
PRODUCT_POST_STATUS VARCHAR(1),
PRODUCT_HOT_DEAL VARCHAR(1),
PRODUCT_POPULAR_DEAL VARCHAR(1),
PRODUCT_CLEARANCE_DEAL VARCHAR(1),
PRODUCT_DISPLAY_ORDER SMALLINT,
PRODUCT_USER_ID INT,
PRODUCT_UPDATED_BY VARCHAR(15),
PRODUCT_POSTED_DT DATETIME  NULL,
PRODUCT_UPDATED_DT DATETIME NULL,
PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE PROD_CATEGORY(
CATEGORY_ID INT  NOT NULL,
CATEGORY_NAME VARCHAR(75),
PRIMARY KEY (CATEGORY_ID)
);

CREATE TABLE MD_USER(
USER_ID INT NOT NULL AUTO_INCREMENT,
USER_NAME VARCHAR(75) NOT NULL,
USER_PWD VARCHAR(100) NOT NULL,
USER_EMAILID VARCHAR(25) NOT NULL,
USER_ROLE_ID INT NOT NULL,
PRIMARY KEY (USER_ID)
);

CREATE TABLE MD_ROLE(
ROLE_ID INT NOT NULL AUTO_INCREMENT,
ROLE_NAME VARCHAR(25) NOT NULL,
PRIMARY KEY (ROLE_ID)
);